### ISSUE TITLE
Countdown clock runs anti-clockwise

### ISSUE THREAD

**Issue by gingerling** [helloworld1/FreeOTPPlus#127]
Hi, I get this sounds fairly superficial but the countdown clock for token expiry time runs anti-clockwise. I'm dyslexic and I actually found this surprisingly hard to handle! It's hard for me to type the numbers in within the time frame anyway, but I really struggle to process how much time is left when the clock runs the wrong way.

I can see why someone would do it this way (how much time is left, so it's like minus time) but really it's also how much time untill the next code, so you could see it that way too!

I suggest that  this be changed to a clockwise animation :)

Thanks for all the work, my first time using the app, worked great so far!

**Comment by helloworld1** [comment]
It is a count down timeer, so it is running the clock backwards like a timer.

**Comment by helloworld1** [comment]
And I totally understand dyslexic or even culture difference to have a preference for the app to behave differently. 
Unfortunately, it requires work and support the different options for a long time. I normally don't have the resource / time to accommodate all.
Since the app is open sourced, it is totally fine to make modification if you or anyone can do it.

**Comment by helloworld1** [comment]
BTW, you do remind me an accessibility item. I don't know the app works if user disables the system animation. I can see some users prefers no animation. But I haven't tested.
