### ISSUE TITLE
Encrypted(?) Storage

### ISSUE THREAD

**Issue by kelna** [helloworld1/FreeOTPPlus#14]
I have some questions: How does the app store keys? And how does it export them to external storage (e.g. GDrive)? Do you employ encryption? Thank you!

**Comment by Lekensteyn** [comment]
The tokens are not encrypted and I think that it is possible to have them backup up (either through `adb backup` or through GDrive).

`allowBackup` is true, which means that external backups and Google backups are allowed:
https://github.com/helloworld1/FreeOTPPlus/blob/e7dfc62363d34972294df741f9cee4027e792342/app/src/main/AndroidManifest.xml#L38-L39

The normal SharedPreferences storage is used with `MODE_PRIVATE`. This just means that other apps cannot access it, but it is not encrypted in any way:
https://github.com/helloworld1/FreeOTPPlus/blob/e7dfc62363d34972294df741f9cee4027e792342/app/src/main/java/org/fedorahosted/freeotp/TokenPersistence.java#L49-L52

To actually employ encryption, the KeyStore API should be used:
https://developer.android.com/reference/java/security/KeyStore

**Comment by kelna** [comment]
> To actually employ encryption, the KeyStore API should be used:

Seems to be a good idea. Does this mean that the original FreeOTP stores the keys unencrypted as well?

**Comment by Lekensteyn** [comment]
> Does this mean that the original FreeOTP stores the keys unencrypted as well?

That is correct, the original FreeOTP implementation also lacks encryption. Their developers are open to implementing it though, indeed using the KeyStore API: https://github.com/freeotp/freeotp-android/issues/6#issuecomment-273248243

There is one PR to implement this, I have not reviewed though and mention it since it was referenced from the previous issue: https://github.com/freeotp/freeotp-android/pull/150

**Comment by helloworld1** [comment]
Yes, encryption support is still on my todo list. I don't think FreeOTP+ can actually use KeyStoreAPI because the data needs to be stored elsewhere and restored on a different device. 
I am thinking about using simpler (weaker) symmetric crypto to just encrypt secret part of the data.
Also I would like to have PIN / fingerprint support which requires quite some more work. If you are aware of any libraries to help the UI of PIN / fingerprint, it would be a great help here.

**Comment by itsKV** [comment]
I don't any coding part. But, while lurking on internet, I came to know about some on the open sourced encryption libraries which can be implemented in android applications very efficiently. 

https://facebook.github.io/conceal/
https://github.com/google/tink
https://android-arsenal.com/details/1/935
https://github.com/google/capillary

Hope, this helps.

**Comment by itsKV** [comment]
encrypting tokens using any of the suggested library with user PIN/fingerprint hash will be sufficient.

**Comment by unicorntaco** [comment]
> encryption support is still on my todo list.

How about lifting from another project?

https://github.com/andOTP/andOTP

**Comment by lemmy04** [comment]
One big advantage of the original FreeOTP is that it uses a decent layout on tablets... see #121

**Comment by helloworld1** [comment]
Let's consolidate the discussion in #128
