### ISSUE TITLE
[Only Hint] Question about using server side application

### ISSUE THREAD

**Issue by danjde** [helloworld1/FreeOTPPlus#54]
Hi Devs and excuse me for the off-topic question.
I'm very newby to 2FA, and I'm searching an application that does not include any subsystem Google.
The matter is very delicate and I would not like to create problems for users during authentication.
Could you simply suggest me the best way using FreeOTPPlus?
I manage some debian (VPS) servers.

Many thanks!

Davide

**Comment by helloworld1** [comment]
For a very simple server side development, you will have an API that generate random strings as secret and then maintain a database that links user id to the secret. 
Then when user want to authenticate, user will give code and server side will fetch user's secret and generate code and then compare with user's given code. If they matches, then pass the authentication otherwise fail it.
The token code generation can be implemented in the same way as FreeOTPPlus does:
https://github.com/helloworld1/FreeOTPPlus/blob/master/app/src/main/java/org/fedorahosted/freeotp/token/Token.java

**Comment by danjde** [comment]
Thanks  helloworld1 for your reply,
the API you reported to me seems to use parts of the Google infrastructure: 

```
import com.google.android.apps.authenticator.Base32String;
import com.google.android.apps.authenticator.Base32String.DecodingException;
```

Thanks anyway!

Davide

**Comment by helloworld1** [comment]
No the code is from FreeOTPPlus. It was originally implemented by Google so I keep the google package name there.

https://github.com/helloworld1/FreeOTPPlus/blob/master/app/src/main/java/com/google/android/apps/authenticator/Base32String.java
