### ISSUE TITLE
Don't align codes strictly with the system clock to improve usability

### ISSUE THREAD

**Issue by wischi-chr** [helloworld1/FreeOTPPlus#95]
Currently the code shown is strictly aligned with the system clock. When one clicks a token (for it to be shown) it happens to me a lot that I see the token for a very brief period of time (less than a few seconds) before a new code is shown.

A way better solution would be to use the click to get the current time, determine how long the code would be valid and if it's less than half of the period just show the next code, plus always show the code for the duration of the period. Another click would just repeat that step and reset the timer. This way a code will always be shown for 30s (or the set period)

Because of they way how OTPs work and the fact that clocks aren't always in perfect sync, servers accept those codes, even if they are slightly in the future or past according to your system clock.

**Comment by helloworld1** [comment]
AFAIK, Google authenticator, Microsoft authenticator used strict clock code so you can have the code for only a few seconds. Since I cannot test all the implementation there, I am not sure if always giving 30s will result in invalid OTP code. 
It would be great you can point out the spec regarding how relax the time would be.
This is what I found from RFC 6238:
<pre>
 Due to network latency, the gap (as measured by T, that
   is, the number of time steps since T0) between the time that the OTP
   was generated and the time that the OTP arrives at the receiving
   system may be large.  The receiving time at the validation system and
   the actual OTP generation may not fall within the same time-step
   window that produced the same OTP.  When an OTP is generated at the
   end of a time-step window, the receiving time most likely falls into
   the next time-step window.  A validation system SHOULD typically set
   a policy for an acceptable OTP transmission delay window for
   validation.  The validation system should compare OTPs not only with
   the receiving timestamp but also the past timestamps that are within
   the transmission delay.  A larger acceptable delay window would
   expose a larger window for attacks.  We RECOMMEND that at most one
   time step is allowed as the network delay.
</pre>

I don't see the delay window is define here and could vary between server implementations. So I probably prefer keeping the strict timing for best compatibility.
